'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Profile = { id: string; display_name: string | null; avatar_path: string | null; age_band: string | null; generation: string | null; gender: string | null; orientation: string | null; country_code: string | null; interface_language: string | null; chat_language: string | null; online_visible: boolean; profile_visible: boolean; generation_visible: boolean; country_visible: boolean; gender_visible: boolean; age_band_visible: boolean; interests_visible: boolean }

export default function ProfilePage() {
  const params = useParams<{ profileId: string }>(); const router = useRouter(); const id = params.profileId
  const [profile,setProfile]=useState<Profile|null>(null); const [own,setOwn]=useState(false); const [status,setStatus]=useState(''); const [error,setError]=useState('')
  useEffect(()=>{ const supabase=createClient(); void (async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/');return} setOwn(user.id===id); const {data,error:e}=await supabase.from('profiles').select('id,display_name,avatar_path,age_band,generation,gender,orientation,country_code,interface_language,chat_language,online_visible,profile_visible,generation_visible,country_visible,gender_visible,age_band_visible,interests_visible').eq('id',id).maybeSingle(); if(e)setError(e.message); else setProfile(data as Profile|null) })() },[id,router])
  async function addFriend(){ const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {error:e}=await supabase.from('friend_requests').insert({sender_id:user.id,receiver_id:id,status:'pending'}); setStatus(e?e.message:'Friend request sent.') }
  if(error)return <main className="min-h-screen bg-slate-950 p-8 text-red-200">{error}</main>
  if(!profile)return <main className="min-h-screen bg-slate-950 p-8 text-slate-400">Loading profile…</main>
  return <main className="min-h-screen bg-slate-950 px-4 py-8 text-white"><div className="mx-auto max-w-xl"><button onClick={()=>router.back()} className="text-sm text-slate-400">← Back</button><section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-7"><div className="flex items-center justify-between"><div><p className="text-sm text-cyan-300">⚡ ShahZap profile</p><h1 className="mt-2 text-3xl font-bold">{profile.display_name ?? 'ShahZap user'}</h1></div>{profile.online_visible&&<span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">Online</span>}</div>{own?<p className="mt-4 text-sm text-slate-400">This is your profile. Use your settings to control discovery and field visibility.</p>:!profile.profile_visible?<p className="mt-4 text-sm text-slate-400">This profile is private.</p>:<div className="mt-6 grid gap-3">{profile.age_band_visible&&profile.age_band&&<div className="rounded-xl bg-slate-950 p-3 text-sm">Age band: {profile.age_band}</div>}{profile.generation_visible&&profile.generation&&<div className="rounded-xl bg-slate-950 p-3 text-sm">Generation: {profile.generation}</div>}{profile.gender_visible&&profile.gender&&<div className="rounded-xl bg-slate-950 p-3 text-sm">Gender: {profile.gender}</div>}{profile.country_visible&&profile.country_code&&<div className="rounded-xl bg-slate-950 p-3 text-sm">Country: {profile.country_code}</div>}{profile.chat_language&&<div className="rounded-xl bg-slate-950 p-3 text-sm">Chat language: {profile.chat_language}</div>}<button onClick={addFriend} className="mt-3 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Add friend</button>{status&&<p className="text-sm text-cyan-200">{status}</p>}</div>}</section></div></main>
}
