'use client'

import { useEffect, useState } from 'react'
import { getRewardWallet, getRewards, redeemReward } from '@/lib/rewards'
import { friendlyError } from '@/lib/errors'
import { AdsterraReward } from '@/components/adsterra-reward'
import { AppHeader } from '@/components/app-header'
import { Gift } from 'lucide-react'

type Reward = { id: string; code: string; title: string; description: string; cost_zap_points: number; reward_type: string; reward_value: number }
type Wallet = { credits: number; passes: { id: string; source: string; started_at: string | null; expires_at: string | null; remaining_seconds: number; status: string }[]; shields: number }

export default function RewardsPage() {
  const [rewards,setRewards]=useState<Reward[]>([]); const [wallet,setWallet]=useState<Wallet|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
  async function load(){ const [r,w]=await Promise.all([getRewards(),getRewardWallet()]); if('error' in r) setError(friendlyError(r.error,'Unable to load rewards.')); else setRewards(r.data); if('error' in w) setError(friendlyError(w.error,'Unable to load wallet.')); else setWallet(w.data) }
  useEffect(()=>{ let active=true; void Promise.all([getRewards(),getRewardWallet()]).then(([r,w])=>{if(!active)return;if('error' in r)setError(friendlyError(r.error,'Unable to load rewards.'));else setRewards(r.data);if('error' in w)setError(friendlyError(w.error,'Unable to load wallet.'));else setWallet(w.data)}); return()=>{active=false} },[])
  async function redeem(code:string){setBusy(code);setError('');const result=await redeemReward(code);if('error' in result)setError(friendlyError(result.error,'Unable to redeem this reward.'));else await load();setBusy('')}
  return <main className="min-h-screen bg-slate-950 text-white"><AppHeader title="Rewards" icon="gift" /><div className="mx-auto max-w-4xl w-full px-4 pb-10 pt-4 lg:max-w-6xl"><p className="text-xs leading-relaxed text-slate-500">Turn Zap Points into perks — applied securely on the server.</p>{error&&<p className="mt-5 rounded-xl bg-red-950/40 p-3 text-sm text-red-200">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-500">Region Credits</p><p className="mt-2 text-2xl font-bold">🌎 {wallet?.credits??0}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-500">Chat Passes</p><p className="mt-2 text-2xl font-bold">🎫 {wallet?.passes.length??0}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-500">Streak Shields</p><p className="mt-2 text-2xl font-bold">🛡️ {wallet?.shields??0}</p></div></div><section className="mt-7"><h2 className="font-semibold">Rewards shop</h2><div className="mt-3 grid gap-4 sm:grid-cols-2">{rewards.map(r=><article key={r.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{r.title}</h3><p className="mt-1 text-sm text-slate-400">{r.description}</p></div><span className="whitespace-nowrap text-sm font-bold text-cyan-300">{r.cost_zap_points} ZP</span></div><button disabled={busy===r.code} onClick={()=>redeem(r.code)} className="mt-5 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">{busy===r.code?'Redeeming…':'Redeem'}</button></article>)}</div></section><section className="mt-7"><h2 className="font-semibold">Chat Passes</h2><div className="mt-4 space-y-3">{wallet?.passes.map(p=><div key={p.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><span className="font-semibold">{p.status==='active'?'⚡ Active Chat Pass':'🎫 30-minute Chat Pass'}</span><span className="text-sm text-slate-400">{Math.ceil(p.remaining_seconds/60)} min</span></div><p className="mt-1 text-xs text-slate-500">Source: {p.source}</p></div>)}{wallet?.passes.length===0&&<p className="text-sm text-slate-500">No active or available passes.</p>}</div></section><section className="mt-10"><h2 className="text-xl font-semibold">Earn a free Chat Pass</h2><div className="mt-4"><AdsterraReward/></div></section></div></main>
}
