'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'

type Audit = { id: string; actor_id: string; action: string; target_type: string | null; target_id: string | null; metadata: Record<string, unknown>; created_at: string }
type Moderation = { id: string; actor_id: string; target_profile_id: string | null; target_message_id: string | null; action: string; reason: string | null; expires_at: string | null; created_at: string }

export default function AdminPage() {
  const router = useRouter(); const [audit,setAudit]=useState<Audit[]>([]); const [actions,setActions]=useState<Moderation[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
  useEffect(()=>{let active=true; async function load(){const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user){router.replace('/');return} const {data:role,error:roleError}=await s.from('admin_roles').select('role').eq('profile_id',user.id).maybeSingle(); if(roleError||!role){setError('Staff access required.');setLoading(false);return} const [a,m]=await Promise.all([s.from('admin_audit_log').select('id,actor_id,action,target_type,target_id,metadata,created_at').order('created_at',{ascending:false}).limit(50),s.from('moderation_actions').select('id,actor_id,target_profile_id,target_message_id,action,reason,expires_at,created_at').order('created_at',{ascending:false}).limit(50)]); if(active){setAudit((a.data??[]) as Audit[]);setActions((m.data??[]) as Moderation[]);setError(a.error?.message??m.error?.message??'');setLoading(false)}} void load();return()=>{active=false}},[router])
  return <main className="min-h-screen bg-slate-950 px-4 py-8 text-white"><div className="mx-auto max-w-6xl"><button onClick={()=>router.push('/app')} className="text-sm text-slate-400">← Back</button><div className="mt-6 flex items-end justify-between"><div><p className="text-sm font-semibold text-cyan-300">ShahZap Operations</p><h1 className="mt-1 text-3xl font-bold">Admin & Moderation</h1><p className="mt-2 text-slate-400">Restricted operational view with audit visibility.</p></div></div>{loading&&<p className="mt-8 text-slate-500">Checking staff access…</p>}{error&&<p className="mt-8 rounded-xl bg-red-950/40 p-4 text-sm text-red-200">{error}</p>}{!loading&&!error&&<div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Recent moderation</h2><div className="mt-4 space-y-3">{actions.length===0?<p className="text-sm text-slate-500">No moderation actions recorded.</p>:actions.map(x=><div key={x.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between gap-3"><span className="font-medium">{x.action}</span><span className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-400">Target: {x.target_profile_id??x.target_message_id??'—'}</p>{x.reason&&<p className="mt-1 text-xs text-slate-500">{x.reason}</p>}</div>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Audit log</h2><div className="mt-4 space-y-3">{audit.length===0?<p className="text-sm text-slate-500">No audit events recorded.</p>:audit.map(x=><div key={x.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between gap-3"><span className="font-medium">{x.action}</span><span className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-400">{x.target_type??'system'} {x.target_id??''}</p></div>)}</div></section></div>}</div></main>
}
