import Link from 'next/link'
import { notFound } from 'next/navigation'

const pages: Record<string, { title: string; description: string; heading: string; sections: [string,string][] }> = {
  'random-chat': { title: 'Random Chat Online', description: 'Discover new conversations with privacy-first random chat on ShahZap.', heading: 'Random Chat Online', sections: [['Meet someone new','ShahZap helps you discover compatible conversations while keeping your profile pseudonymous.'],['Matching first, random fallback','Safety and compatibility are considered before the system broadens matching and falls back to a compatible random conversation.']] },
  'anonymous-chat': { title: 'Anonymous Chat', description: 'Have pseudonymous conversations with new people on ShahZap.', heading: 'Anonymous Chat With Privacy in Mind', sections: [['Pseudonymous by design','You can use a generated identity and control profile visibility. ShahZap does not present anonymous chat as absolute anonymity.'],['Your controls','Blocking, reporting and privacy settings are built into the product.']] },
  'chat-with-strangers': { title: 'Chat With Strangers', description: 'Meet new people through moderated random conversations.', heading: 'Chat With Strangers', sections: [['A conversation, not a directory','Start a new conversation without exposing private application data to search engines.'],['Safety matters','Age compatibility, blocking, reporting and moderation are part of the experience.']] },
  'gender-chat': { title: 'Gender Matching Chat', description: 'Use gender and orientation preferences as part of ShahZap matching.', heading: 'Gender & Orientation Matching', sections: [['Your preference','Gender and orientation preferences can guide compatible matching.'],['Safety remains separate','Preferences never replace age and safety compatibility rules.']] },
  'country-chat': { title: 'Country Chat', description: 'Discover conversations by geographic preference with ShahZap.', heading: 'Country & Region Chat', sections: [['Geographic discovery','Region targeting can help you discover people from places you choose.'],['Premium and Region Credits','Geographic targeting is an optional product capability and is kept separate from basic safety matching.']] },
  'translate-chat': { title: 'Chat With Translation', description: 'Chat across languages with ShahZap automatic translation architecture.', heading: 'Chat Across Languages', sections: [['Separate UI and chat languages','Your interface language and preferred chat language can be configured independently.'],['Original messages matter','Translations are designed alongside the original message rather than replacing it.']] },
  'meet-new-people': { title: 'Meet New People', description: 'Make new connections through ShahZap social discovery.', heading: 'Meet New People', sections: [['Find a conversation','ShahZap combines preferences, interests and compatibility to help start conversations.'],['Keep useful connections','Friends, profiles and privacy controls continue after a conversation.']] },
  'how-it-works': { title: 'How ShahZap Works', description: 'Learn how ShahZap matching, chat, safety and progression work.', heading: 'How ShahZap Works', sections: [['1. Set preferences','Choose the information you want the matching system to use.'],['2. Match','Safety and compatibility come before broader matching and fallback.'],['3. Chat','Start a real-time conversation with translation support.'],['4. Continue','You can make friends, earn progression and use rewards.']] },
  'safety': { title: 'Safety', description: 'Learn about ShahZap reporting, blocking, privacy and moderation.', heading: 'Safety on ShahZap', sections: [['Report and block','Users can report problems and block people they do not want to interact with.'],['Moderation','Staff moderation and audit systems provide operational controls for confirmed violations.']] },
  'privacy': { title: 'Privacy', description: 'Understand ShahZap privacy, pseudonymous profiles and visibility controls.', heading: 'ShahZap Privacy', sections: [['Pseudonymous, not a promise of absolute anonymity','Infrastructure may process information needed for authentication, abuse prevention, moderation and service operation.'],['Control visibility','Profile visibility and blocking help users control who can discover or interact with them.']] },
  'faq': { title: 'FAQ', description: 'Frequently asked questions about ShahZap.', heading: 'Frequently Asked Questions', sections: [['Is ShahZap anonymous?','It is designed around pseudonymous social discovery, not absolute anonymity.'],['Does ShahZap translate chats?','The product supports a separate chat-language preference and translation architecture.'],['Can I block someone?','Yes. Blocking and reporting are core safety controls.']] },
  'about': { title: 'About ShahZap', description: 'Learn about the ShahZap social discovery product.', heading: 'About ShahZap', sections: [['The idea','ShahZap is designed as a social discovery ecosystem combining random chat, intelligent matching, translation, safety, progression and rewards.'],['The principle','The public website explains the product while private conversations remain outside the public SEO layer.']] },
  'blog': { title: 'ShahZap Blog', description: 'Guides and product education from ShahZap.', heading: 'ShahZap Blog', sections: [['How to stay safe while chatting online','Learn why blocking, reporting, privacy controls and thoughtful conversations matter.'],['How anonymous chat works','Understand pseudonymous profiles and why privacy does not mean absolute anonymity.'],['How translation helps international chat','Explore how separate interface and chat languages can make cross-language conversations easier.']] },
}

export function generateStaticParams() { return Object.keys(pages).map(slug => ({ slug })) }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; return page ? { title: page.title, description: page.description, alternates: { canonical: `/${slug}` }, openGraph: { title: page.title, description: page.description, url: `/${slug}`, type: 'website' } } : {} }

export default async function PublicPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; if (!page) notFound(); return <main className="min-h-screen bg-slate-950 px-5 py-16 text-white"><article className="mx-auto max-w-4xl"><Link href="/" className="text-sm text-cyan-300">← ShahZap</Link><h1 className="mt-8 text-4xl font-bold sm:text-5xl">{page.heading}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">{page.description}</p><div className="mt-12 grid gap-5 sm:grid-cols-2">{page.sections.map(([title,text])=><section key={title} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-slate-400">{text}</p></section>)}</div><Link href="/app" className="mt-10 inline-block rounded-xl bg-cyan-400 px-6 py-3 font-bold text-slate-950">Start ShahZap</Link></article></main> }
