create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_path text,
  age_band text not null check (age_band in ('under_13','13_15','16_17','18_20','21_29','30_44','45_59','60_plus')),
  generation text check (generation in ('gen_alpha','gen_z','millennial','gen_x','boomer')),
  gender text,
  orientation text,
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  interface_language text not null default 'en',
  chat_language text not null default 'en',
  online_visible boolean not null default false,
  profile_visible boolean not null default true,
  generation_visible boolean not null default false,
  country_visible boolean not null default false,
  gender_visible boolean not null default true,
  age_band_visible boolean not null default true,
  interests_visible boolean not null default true,
  xp bigint not null default 0 check (xp >= 0),
  zap_points bigint not null default 0 check (zap_points >= 0),
  region_credits bigint not null default 0 check (region_credits >= 0),
  level integer not null default 1 check (level >= 1),
  streak_days integer not null default 0 check (streak_days >= 0),
  last_active_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interests (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text,
  active boolean not null default true
);

create table if not exists public.profile_interests (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, interest_id)
);

create table if not exists public.match_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  preferred_age_bands text[] not null default '{}',
  preferred_genders text[] not null default '{}',
  preferred_orientations text[] not null default '{}',
  preferred_generations text[] not null default '{}',
  preferred_languages text[] not null default '{}',
  preferred_countries text[] not null default '{}',
  interest_wait_seconds integer not null default 15 check (interest_wait_seconds in (5,10,15,30,45,60)),
  country_targeting_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);
create unique index if not exists friend_requests_pending_unique on public.friend_requests(sender_id, receiver_id) where status = 'pending';

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'active' check (status in ('matching','active','completed','aborted','moderated')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  retained_until timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (conversation_id, profile_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  original_message text not null check (char_length(original_message) <= 5000),
  original_language text,
  translated_message text,
  target_language text,
  moderation_status text not null default 'pending' check (moderation_status in ('pending','allowed','flagged','removed')),
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_profile_id uuid not null references public.profiles(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null,
  reason text not null check (reason in ('harassment','spam','hate_speech','sexual_content','scam','impersonation','underage_concern','threatening_behavior','other')),
  details text,
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (reporter_id <> reported_profile_id)
);

create table if not exists public.reward_ledger (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  currency text not null check (currency in ('xp','zap_points','region_credits','reward_tokens')),
  amount bigint not null,
  reason text not null,
  reference_type text,
  reference_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_passes (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  duration_seconds integer not null default 1800 check (duration_seconds > 0),
  remaining_seconds integer not null default 1800 check (remaining_seconds >= 0),
  started_at timestamptz,
  expires_at timestamptz,
  status text not null default 'available' check (status in ('available','active','expired','consumed')),
  source text not null check (source in ('rewarded_ad','zap_points','reward','premium')),
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_id uuid not null references public.profiles(id) on delete cascade,
  code text not null,
  qualified_at timestamptz,
  rewarded_at timestamptz,
  created_at timestamptz not null default now(),
  check (referrer_id <> referred_id),
  unique (referrer_id, referred_id)
);

create table if not exists public.admin_settings (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

create index if not exists profiles_online_idx on public.profiles(online_visible, last_active_at desc);
create index if not exists profiles_age_idx on public.profiles(age_band);
create index if not exists messages_conversation_idx on public.messages(conversation_id, created_at);
create index if not exists participants_profile_idx on public.conversation_participants(profile_id, joined_at desc);
create index if not exists reports_status_idx on public.reports(status, created_at desc);
create index if not exists reward_ledger_profile_idx on public.reward_ledger(profile_id, created_at desc);
create index if not exists chat_pass_profile_status_idx on public.chat_passes(profile_id, status, created_at desc);

create or replace function public.set_updated_at() returns trigger
language plpgsql security invoker set search_path = public
as $$ begin new.updated_at = now(); return new; end; $$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists preferences_set_updated_at on public.match_preferences;
create trigger preferences_set_updated_at before update on public.match_preferences for each row execute function public.set_updated_at();
drop trigger if exists friend_requests_set_updated_at on public.friend_requests;
create trigger friend_requests_set_updated_at before update on public.friend_requests for each row execute function public.set_updated_at();
drop trigger if exists admin_settings_set_updated_at on public.admin_settings;
create trigger admin_settings_set_updated_at before update on public.admin_settings for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.interests enable row level security;
alter table public.profile_interests enable row level security;
alter table public.match_preferences enable row level security;
alter table public.blocks enable row level security;
alter table public.friend_requests enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.reward_ledger enable row level security;
alter table public.chat_passes enable row level security;
alter table public.referrals enable row level security;
alter table public.admin_settings enable row level security;

insert into public.interests(slug,name,category) values
('gaming','Gaming','Entertainment'),('music','Music','Entertainment'),('movies','Movies','Entertainment'),('anime','Anime','Entertainment'),('books','Books','Learning'),('coding','Coding','Technology'),('art','Art','Creative'),('sports','Sports','Lifestyle'),('travel','Travel','Lifestyle'),('food','Food','Lifestyle'),('fitness','Fitness','Lifestyle'),('photography','Photography','Creative'),('memes','Memes','Entertainment'),('science','Science','Learning'),('technology','Technology','Technology'),('nature','Nature','Lifestyle')
on conflict (slug) do nothing;

insert into public.admin_settings(key,value,description) values
('free_gender_matching','true','Allow gender preference matching on the free tier'),
('free_orientation_matching','true','Allow orientation preference matching on the free tier'),
('country_targeting','premium','Country/region targeting entitlement'),
('interest_wait_seconds','[5,10,15,30,45,60]','Allowed interest matching wait times'),
('chat_pass_seconds','1800','Default rewarded-ad chat pass duration'),
('chat_retention_days','7','Temporary moderation retention window'),
('online_directory','true','Allow users to opt into the online directory'),
('friend_requests','true','Enable friend requests'),
('profile_photos','true','Enable profile avatars subject to moderation')
on conflict (key) do nothing;

alter publication supabase_realtime add table public.messages;
