-- ZapBot + ZapGuide practice partners — guarantees every user can reach a chat.
--
-- Problem: matching pairs two users queued at the same moment. A solo visitor
-- could never reach /chat/<id> by any path. Additionally, client-triggered bot
-- replies proved fragile (old bundles, swallowed RPC errors), leaving users
-- staring at a typing indicator with no answer.
--
-- Final architecture — replies are generated by a DATABASE TRIGGER, so no
-- client involvement can break them:
--   * ZapBot   ⚡ casual practice partner (small talk brains);
--   * ZapGuide 🧭 site expert that explains how every ShahZap feature works;
--   * private.bot_reply(conv_id, actor) — persona-aware rule engine
--     (SECURITY DEFINER; participant checks; one reply per human message;
--     30-reply cap per conversation then nudges toward real matching);
--   * AFTER INSERT trigger on public.messages fires the engine automatically
--     for 2-person conversations whose partner is a bot. The trigger wraps the
--     engine in an exception-safe block so a bot failure can NEVER fail the
--     user's own message insert;
--   * thin definer wrappers public.zap_bot_reply / public.guide_bot_reply are
--     kept for manual nudges and debugging (granted to authenticated only);
--   * both bot accounts: created via anonymous sign-up (valid auth.users row),
--     then hardened (confirmed internal email, is_anonymous=false, no usable
--     credentials) with visible profiles kept online by pg_cron heartbeat.

-- ══════════════════════════════ IDs ══════════════════════════════
-- ZapBot:   6b275e80-98e2-4e09-96b2-cb50a4a64461
-- ZapGuide: 5ec6df08-8aa6-4328-a388-42ec172bdd47

-- ═══════════════════ Engine (persona-aware) ═══════════════════
create or replace function private.bot_reply(p_conversation_id uuid, p_actor uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  bot_a uuid := '6b275e80-98e2-4e09-96b2-cb50a4a64461';
  bot_b uuid := '5ec6df08-8aa6-4328-a388-42ec172bdd47';
  uid uuid := coalesce(p_actor, auth.uid());
  partner_bot uuid;
  me_count int;
  last_msg record;
  bot_msg_count int;
  reply_text text;
  t text;
begin
  if uid is null then raise exception 'unauthorized'; end if;

  select count(*) into me_count from public.conversation_participants cp
  where cp.conversation_id = p_conversation_id and cp.profile_id = uid;
  if me_count = 0 then raise exception 'conversation_not_found'; end if;

  select count(*) into me_count from public.conversation_participants cp
  where cp.conversation_id = p_conversation_id;
  if me_count <> 2 then raise exception 'not_a_bot_chat'; end if;

  select cp.profile_id into partner_bot from public.conversation_participants cp
  where cp.conversation_id = p_conversation_id and cp.profile_id in (bot_a, bot_b);
  if partner_bot is null or partner_bot = uid then raise exception 'not_a_bot_chat'; end if;

  select * into last_msg from public.messages m
  where m.conversation_id = p_conversation_id order by m.created_at desc limit 1;
  if last_msg is null or last_msg.sender_id = partner_bot then
    return jsonb_build_object('replied', false);
  end if;

  select count(*) into bot_msg_count from public.messages m
  where m.conversation_id = p_conversation_id and m.sender_id = partner_bot;

  t := lower(last_msg.original_message);

  if bot_msg_count >= 30 then
    reply_text := 'We have chatted a lot 😊 If you have questions about ShahZap I am still here — otherwise hit Start matching to meet someone real!';
  elsif partner_bot = bot_b then
    -- ── ZapGuide: site-expert brain ──
    case
      when t ~ '(^|[[:space:]])?(hi+|hello+|hey+|salam|hola|namaste|yo+)([[:space:]]|[[:punct:]]|$)' then
        reply_text := 'Hi! 👋 I am ZapGuide 🧭 I know everything about how ShahZap works. Ask me things like: How does matching work? · What are Zap Points? · How do I get a Chat Pass? · Is ShahZap private?';
      when t ~ '(how.*(match|matching|work|start|talk|chat)|match)' then
        reply_text := 'Matching, step by step ⚡ 1) Open Start matching — you enter a queue with your preferences (language, age band, interests). 2) When another member waits at the same moment, the engine pairs you safety-first (age compatibility), then preferences, then interests — safe random fallback after your wait time. 3) You land straight in a private chat. Nobody waiting? A practice-chat button appears automatically.';
      when t ~ '(pass|rewarded|ad\b|watch.*ad|free chat)' then
        reply_text := 'Chat Passes 🎫 Open Rewards → watch a short rewarded ad → a 30-minute Chat Pass is granted server-side (one per 30 minutes). Active conversations are never interrupted by ads.';
      when t ~ '(zap point|\bxp\b|level|streak|progression|quest|mission)' then
        reply_text := 'Progression 🎮 Meaningful activity earns XP and Zap Points (Progression page): levels track your journey, streaks reward showing up, Missions list bonus goals. Spend Zap Points in the Rewards shop.';
      when t ~ '(region credit|country|region|geo|target)' then
        reply_text := 'Region targeting 🌎 In Settings enable country targeting to prefer matches from chosen regions. It runs on Region Credits and is part of Premium perks — safety matching always stays free.';
      when t ~ '(premium|subscri|price|pay|paddle|upgrade)' then
        reply_text := 'Premium 💎 Unlocks ad-free chatting plus country targeting. Monthly/yearly plans run through Paddle checkout on the Premium page — entitlements verified server-side via webhooks.';
      when t ~ '(privacy|private|anonym|data|delete account|gdpr)' then
        reply_text := 'Privacy 🛡️ ShahZap is pseudonymous: no email or name needed — just a nickname. Every profile field has its own visibility toggle in Settings, exact ages are never shown, chats stay private, and one tap blocks or reports anyone.';
      when t ~ '(translat|language|urdu|english|multilingual)' then
        reply_text := 'Languages 🌐 Interface language and chat language are set separately (onboarding or Settings). Chats keep the original message alongside any translation, so nothing gets lost.';
      when t ~ '(friend|request|connect)' then
        reply_text := 'Friends 🤝 Tap Add friend on a profile or the + icon in the Online list. They accept from their Friends page; accepted friends get a direct-chat shortcut anytime.';
      when t ~ '(online|directory|active now|green dot)' then
        reply_text := 'Online now 🟢 Members who opted into the directory and were active within 5 minutes appear there. Tap anyone for an instant direct chat. Toggle yourself via Show me online in Settings.';
      when t ~ '(install|pwa|app|mobile|phone|home screen)' then
        reply_text := 'Install like an app 📱 ShahZap is a PWA: Android/Chrome → menu Add to Home Screen; iOS Safari → Share → Add to Home Screen. Full-screen app-like experience.';
      when t ~ '(report|block|abuse|harrass|harass|moderat|spam|scam)' then
        reply_text := 'Safety tools 🚩 Inside every chat: Report (reason + details) and Block — blocked members can never match you again. Reports reach staff moderation with audit logging.';
      when t ~ '(referr|invite|share link|promo)' then
        reply_text := 'Inviting 💌 Share shahzap.safiullahkorai.com — more people online means faster matches for everyone. A structured referral-rewards program is on the roadmap.';
      when t ~ '(who are you|what are you|what is shahzap|about)' then
        reply_text := 'I am ZapGuide 🧭 ShahZaps built-in helper. ShahZap is privacy-first social discovery: anonymous random chat, smart matching across languages, rewards, strong safety controls. Ask how any part works!';
      when last_msg.original_message ~ '\?' then
        reply_text := (array[
          'Good question! Try asking about: matching · Chat Passes · Zap Points · privacy · friends · installing the app.',
          'I cover how ShahZap works — e.g. How does matching work? or What are Zap Points?',
          'Hmm, rephrase that? I know best: matching, rewards, premium, privacy, safety, installation.'
        ])[1+floor(random()*3)];
      else
        reply_text := (array[
          'Got it 🙂 Fun fact: I can explain any part of ShahZap — matching, Chat Passes, Zap Points, privacy… just ask!',
          'Noted! ✨ Tip: ask me how matching works or how to earn Zap Points.',
          'Cool! 😄 Meanwhile: Start matching pairs you with someone new whenever others are online.'
        ])[1+floor(random()*3)];
    end case;
  else
    -- ── ZapBot: casual practice brain ──
    case
      when t ~ '(^|[[:space:]])?(hi+|hello+|hey+|salam|hola|namaste|yo+)([[:space:]]|[[:punct:]]|$)' then
        reply_text := (array[
          'Hey there! I am ZapBot ⚡ your practice partner. How is your day going?',
          'Hello hello! 👋 Great to meet you. What is on your mind today?',
          'Hi! ⚡ Nice to meet you. Tell me something fun about yourself.'
        ])[1+floor(random()*3)];
      when t ~ '(how are|how.r.you|kaise|kya haal|whats up|what.s up)' then
        reply_text := (array[
          'Doing great, zapping along happily ⚡ How about you?',
          'All charged up! 😄 What have you been up to lately?',
          'Pretty good! Tell me — what was the best part of your day?'
        ])[1+floor(random()*3)];
      when t ~ 'thank' then
        reply_text := (array[
          'Anytime! 💙 Practicing with you is fun.',
          'You are very welcome! Want to try chatting with a real person next?'
        ])[1+floor(random()*2)];
      when t ~ '(bye|good ?night|see (you|ya)|gotta go|talk later)' then
        reply_text := 'It was great chatting with you! 👋 Come back anytime — real matches are waiting under Start matching.';
      when last_msg.original_message ~ '\?' then
        reply_text := (array[
          'Ooh good question! As a practice bot I do not know much — ZapGuide 🧭 knows everything about this site though!',
          'Hmm 🤔 I am just a little practice bot. A real human would answer that way better!',
          'Big question! I mostly do small talk ⚡ but someone out there knows.'
        ])[1+floor(random()*3)];
      when t ~ '''(i am|i''m|my name)|^i am |^my name ' then
        reply_text := 'Lovely to meet you! 💙 I am ZapBot, here so nobody ever has to chat alone on ShahZap.';
      else
        reply_text := (array[
          'Tell me more about that! 🙂',
          'Interesting! How did that make you feel?',
          'That sounds cool ⚡ What happened next?',
          'I hear you! What else is going on today?',
          'Nice one 😄 So what brings you to ShahZap today?'
        ])[1+floor(random()*5)];
    end case;
  end if;

  insert into public.messages (conversation_id, sender_id, original_message, moderation_status)
  values (p_conversation_id, partner_bot, reply_text, 'allowed');

  update public.profiles set last_active_at = now() where id = partner_bot;
  return jsonb_build_object('replied', true);
end
$fn$;

-- ═══════════════════ Auto-reply trigger ═══════════════════
create or replace function private.messages_bot_autoreply()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  partner uuid;
  cnt int;
begin
  select cp.profile_id into partner from public.conversation_participants cp
  where cp.conversation_id = NEW.conversation_id and cp.profile_id in ('6b275e80-98e2-4e09-96b2-cb50a4a64461', '5ec6df08-8aa6-4328-a388-42ec172bdd47');
  if partner is null or partner = NEW.sender_id then return NEW; end if;

  select count(*) into cnt from public.conversation_participants cp
  where cp.conversation_id = NEW.conversation_id;
  if cnt <> 2 then return NEW; end if;

  begin
    perform private.bot_reply(NEW.conversation_id, NEW.sender_id);
  exception when others then
    return NEW;  -- a bot failure must never fail the user's message
  end;
  return NEW;
end
$fn$;

drop trigger if exists messages_bot_autoreply on public.messages;
create trigger messages_bot_autoreply
after insert on public.messages
for each row
when (new.sender_id <> all (array['6b275e80-98e2-4e09-96b2-cb50a4a64461'::uuid, '5ec6df08-8aa6-4328-a388-42ec172bdd47'::uuid]))
execute function private.messages_bot_autoreply();

-- ═══════════════════ Manual-nudge wrappers ═══════════════════
create or replace function public.zap_bot_reply(p_conversation_id uuid)
returns jsonb language plpgsql security definer set search_path = public
as $f$ begin return private.bot_reply(p_conversation_id, null); end $f$;

create or replace function public.guide_bot_reply(p_conversation_id uuid)
returns jsonb language plpgsql security definer set search_path = public
as $f$ begin return private.bot_reply(p_conversation_id, null); end $f$;

revoke all on function public.zap_bot_reply(uuid) from public, anon;
grant execute on function public.zap_bot_reply(uuid) to authenticated;
revoke all on function public.guide_bot_reply(uuid) from public, anon;
grant execute on function public.guide_bot_reply(uuid) to authenticated;

-- ═══════════════════ Always-online heartbeat ═══════════════════
select cron.unschedule('zapbot-heartbeat')
where exists (select 1 from cron.job where jobname = 'zapbot-heartbeat');

select cron.schedule(
  'zapbot-heartbeat',
  '* * * * *',
  'update public.profiles set last_active_at = now() where id in (''6b275e80-98e2-4e09-96b2-cb50a4a64461'', ''5ec6df08-8aa6-4328-a388-42ec172bdd47'')'
);
